## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]

## Buttons
set_property PACKAGE_PIN W19 [get_ports i_btn_l]
set_property IOSTANDARD LVCMOS33 [get_ports i_btn_l]
set_property PACKAGE_PIN T17 [get_ports i_btn_r]
set_property IOSTANDARD LVCMOS33 [get_ports i_btn_r]
set_property PACKAGE_PIN T18 [get_ports i_btn_u]
set_property IOSTANDARD LVCMOS33 [get_ports i_btn_u]
set_property PACKAGE_PIN U17 [get_ports i_btn_d]
set_property IOSTANDARD LVCMOS33 [get_ports i_btn_d]
set_property PACKAGE_PIN U18 [get_ports i_btn_c]
set_property IOSTANDARD LVCMOS33 [get_ports i_btn_c]

## Switches
set_property PACKAGE_PIN V17 [get_ports {i_sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {i_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {i_sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[2]}]
set_property PACKAGE_PIN W17 [get_ports {i_sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[3]}]
set_property PACKAGE_PIN W15 [get_ports {i_sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[4]}]
set_property PACKAGE_PIN V15 [get_ports {i_sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[5]}]
set_property PACKAGE_PIN W14 [get_ports {i_sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[6]}]
set_property PACKAGE_PIN W13 [get_ports {i_sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[7]}]
set_property PACKAGE_PIN V2 [get_ports {i_sw[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[8]}]
set_property PACKAGE_PIN T3 [get_ports {i_sw[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[9]}]
set_property PACKAGE_PIN T2 [get_ports {i_sw[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[10]}]
set_property PACKAGE_PIN R3 [get_ports {i_sw[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[11]}]
set_property PACKAGE_PIN W2 [get_ports {i_sw[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[12]}]
set_property PACKAGE_PIN U1 [get_ports {i_sw[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[13]}]
set_property PACKAGE_PIN T1 [get_ports {i_sw[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[14]}]
set_property PACKAGE_PIN R2 [get_ports {i_sw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_sw[15]}]

## 7-segment display
set_property PACKAGE_PIN U2 [get_ports {o_hex_select[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex_select[0]}]
set_property PACKAGE_PIN U4 [get_ports {o_hex_select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex_select[1]}]
set_property PACKAGE_PIN V4 [get_ports {o_hex_select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex_select[2]}]
set_property PACKAGE_PIN W4 [get_ports {o_hex_select[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex_select[3]}]
set_property PACKAGE_PIN W7 [get_ports {o_hex[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex[0]}]
set_property PACKAGE_PIN W6 [get_ports {o_hex[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex[1]}]
set_property PACKAGE_PIN U8 [get_ports {o_hex[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex[2]}]
set_property PACKAGE_PIN V8 [get_ports {o_hex[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex[3]}]
set_property PACKAGE_PIN U5 [get_ports {o_hex[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex[4]}]
set_property PACKAGE_PIN V5 [get_ports {o_hex[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex[5]}]
set_property PACKAGE_PIN U7 [get_ports {o_hex[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex[6]}]
set_property PACKAGE_PIN V7 [get_ports {o_hex[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_hex[7]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {o_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[0]}]
set_property PACKAGE_PIN E19 [get_ports {o_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[1]}]
set_property PACKAGE_PIN U19 [get_ports {o_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[2]}]
set_property PACKAGE_PIN V19 [get_ports {o_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[3]}]
set_property PACKAGE_PIN W18 [get_ports {o_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[4]}]
set_property PACKAGE_PIN U15 [get_ports {o_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[5]}]
set_property PACKAGE_PIN U14 [get_ports {o_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[6]}]
set_property PACKAGE_PIN V14 [get_ports {o_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[7]}]
set_property PACKAGE_PIN V13 [get_ports {o_led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[8]}]
set_property PACKAGE_PIN V3 [get_ports {o_led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[9]}]
set_property PACKAGE_PIN W3 [get_ports {o_led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[10]}]
set_property PACKAGE_PIN U3 [get_ports {o_led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[11]}]
set_property PACKAGE_PIN P3 [get_ports {o_led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[12]}]
set_property PACKAGE_PIN N3 [get_ports {o_led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[13]}]
set_property PACKAGE_PIN P1 [get_ports {o_led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[14]}]
set_property PACKAGE_PIN L1 [get_ports {o_led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[15]}]

## QSPI Flash
set_property PACKAGE_PIN D18 [get_ports qspi_dq0]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_dq0]
set_property PACKAGE_PIN D19 [get_ports qspi_dq1]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_dq1]
set_property PACKAGE_PIN G18 [get_ports qspi_dq2]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_dq2]
set_property PACKAGE_PIN F18 [get_ports qspi_dq3]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_dq3]
set_property PACKAGE_PIN K19 [get_ports qspi_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_cs_n]
