@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Mar 22 19:50:03 -0300 2026
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_bram_only_behav -key {Behavioral:sim_1:Functional:tb_bram_only} -tclbatch tb_bram_only.tcl -view C:/Users/gusta/Documents/Doutorado_UFRN/Desenvolvimento/PyFPGA/teste_AXI/test_AXI.sim/sim_1/behav/xsim/tb_mem_data_behav.wcfg -log simulate.log"
call xsim  tb_bram_only_behav -key {Behavioral:sim_1:Functional:tb_bram_only} -tclbatch tb_bram_only.tcl -view C:/Users/gusta/Documents/Doutorado_UFRN/Desenvolvimento/PyFPGA/teste_AXI/test_AXI.sim/sim_1/behav/xsim/tb_mem_data_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
